package com.kitchen.inventory.enums;

public enum PermissionName {
    // User Management
    USER_READ, USER_CREATE, USER_UPDATE, USER_DELETE,
    // Role Management
    ROLE_READ, ROLE_CREATE, ROLE_UPDATE, ROLE_DELETE,
    // Ingredient Management
    INGREDIENT_READ, INGREDIENT_CREATE, INGREDIENT_UPDATE, INGREDIENT_DELETE,
    // Supplier Management
    SUPPLIER_READ, SUPPLIER_CREATE, SUPPLIER_UPDATE, SUPPLIER_DELETE,
    // Purchase Management
    PURCHASE_READ, PURCHASE_CREATE, PURCHASE_UPDATE, PURCHASE_DELETE, PURCHASE_APPROVE,
    // Inventory Management
    INVENTORY_READ, INVENTORY_CREATE, INVENTORY_UPDATE, INVENTORY_DELETE, INVENTORY_ADJUST,
    // Recipe Management
    RECIPE_READ, RECIPE_CREATE, RECIPE_UPDATE, RECIPE_DELETE,
    // Report Access
    REPORT_VIEW, REPORT_EXPORT,
    // Dashboard Access
    DASHBOARD_VIEW,
    // Kitchen Management
    KITCHEN_READ, KITCHEN_CREATE, KITCHEN_UPDATE, KITCHEN_DELETE,
    // Warehouse Management
    WAREHOUSE_READ, WAREHOUSE_CREATE, WAREHOUSE_UPDATE, WAREHOUSE_DELETE
}
